terraform-routeros/terraform-provider-routeros

.github/workflows/release.yml

Create github actions. Ref #20

Create github actions

---

README.md
docs/index.md
templates/index.md.tmpl

docs(#57): Add instructions for enabling web-ssl service on router

---

client/ipv6_neighbor_discovery.go
client/ipv6_neighbor_discovery_test.go
routeros/provider.go
routeros/resource_ipv6_neighbor_discovery.go

This seemed to work well during minimal testing, it could use a thorough review though.
I also couldn't get the doc generation to work, so you may need to add those.

Add ipv6_neighbor_discovery

---

routeros/mikrotik_client_rest.go
routeros/provider.go
routeros/resource_default_actions.go

Fixed escaping spaces in URL, need to test on old API!
Fixed incorrect error output when parsing JSON.
Fixed informative debug messages.

fix: Spaces in resource names (#102 - #104).

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/ci-pipeline-issue.md
.github/ISSUE_TEMPLATE/documentation-update.md
.github/ISSUE_TEMPLATE/feature_request.md

Set issues as unassigned by default

chore: Update issue templates

---

routeros/resource_ip_dhcp_server_lease.go

fix(#110): Typo in hostname field for dhcp lease

---

routeros/resource_interface_list.go

fix(#121) "builtin" not found.

---

routeros/resource_interface_list_member.go

fix(#122): Add missing fields to interface list member

---

routeros/resource_ip_dhcp_server.go

fix(#110) Add a default value for the "bootp_support" field

---

routeros/resource_interface_wireguard_peer.go

fix(#123) Removed IP address validation.

---

routeros/resource_ip_dns_record.go

Fixes #140
Description: https://github.com/terraform-routeros/terraform-provider-routeros/issues/140#issuecomment-1454045603

fix(#140) Fix imports for static DNS records

---

routeros/resource_interface_wireguard_peer.go

fix(#144) routeros_wireguard_peer error while setting `persistent_keepalive`

---

routeros/resource_ip_route.go

fix: /ip/route - field disabled missing

---

.github/workflows/module_testing.yml

ci: Add RouterOS 7.8 to test workflow

---

examples/resources/routeros_ipv6_route/import.sh
examples/resources/routeros_ipv6_route/resource.tf
routeros/provider.go
routeros/resource_ipv6_route.go
routeros/resource_ipv6_route_test.go

Add routeros_ipv6_route + doc examples with typo fix in test

feat(ipv6): Add routeros_ipv6_route v2

---

routeros/resource_ip_dns_record.go
routeros/resource_ip_dns_record_test.go

fix: routeros_dns_record does not change resource type and data correctly after #158

---

.github/workflows/module_testing.yml
routeros/mikrotik_serialize.go
routeros/resource_ip_dns.go
routeros/resource_ip_dns_test.go

Fixes #174
Change desealization for empty string fields, lists and sets

fix: dns servers cannot be removed

---

routeros/provider_schema_helpers.go
routeros/resource_ip_firewall_mangle.go

Vaerh/issue175, Vaerh/issue178

---

routeros/resource_ip_route.go
routeros/resource_ipv6_address_test.go

fix: ip/route dst_address should not be mandatory

---

routeros/resource_ip_route.go
routeros/resource_ip_route_test.go

fix: Add `check_gateway` field to `routeros_ip_route`

---

routeros/resource_ip_dhcp_client.go

fix: Warnings for primary and secondary ntp

---

examples/resources/routeros_ip_service/import.sh
examples/resources/routeros_ip_service/resource.tf
routeros/provider.go
routeros/resource_ip_service.go
routeros/resource_ip_service_test.go

feat: Support for ip/services

---

examples/resources/routeros_system_user/import.sh
examples/resources/routeros_system_user/resource.tf
routeros/provider.go
routeros/resource_system_user.go
routeros/resource_system_user_test.go

feat: Support creating users

---

routeros/mikrotik_serialize.go
routeros/resource_bgp_connection.go

fix: nil pointer on bgp

---

routeros/datasource_ip_addresses.go
routeros/datasource_ip_routes.go
routeros/resource_capsman_configuration_test.go

fix: Field 'comment' not found in the schema

---

examples/resources/routeros_ip_firewall_mangle/resource.tf

fix: Wrong field names in example files

---

.github/workflows/release.yml

fix(docs): Update release.yml

---

routeros/resource_ip_firewall_filter.go
routeros/resource_ip_firewall_mangle.go
routeros/resource_ip_firewall_nat.go

fix: Patching firewall rules with place_before

---

docs/resources/ip_address.md

Fixes https://github.com/terraform-routeros/terraform-provider-routeros/issues/273

Update routeros_ip_address doc example usage to reflect actual behavior

---

routeros/resource_ovpn_server.go

fix: Unexpected value: aes256 for RouterOS v7.7

---

examples/resources/routeros_interface_dot1x_client/import.sh
examples/resources/routeros_interface_dot1x_client/resource.tf
examples/resources/routeros_interface_dot1x_server/import.sh
examples/resources/routeros_interface_dot1x_server/resource.tf
routeros/provider.go
routeros/resource_interface_dot1x.go

This PR adds support for 802.1x client and server resources. The schema is the same in `6.x` and `7.x`.

feat: Add 802.1X resources

---

examples/resources/routeros_system_ntp_server/import.sh
examples/resources/routeros_system_ntp_server/resource.tf
routeros/provider.go
routeros/resource_system_ntp_server.go
routeros/resource_system_ntp_server_test.go

feat(/system/ntp/server): Add NTP Server resource

---

routeros/resource_interface_ethernet.go

fix: Add 2.5Gbps to validation set

---

routeros/provider_schema_helpers.go

fix(helpers): Fix the style of writing filter parameters

---

examples/resources/routeros_routing_filter_rule/import.sh
examples/resources/routeros_routing_filter_rule/resource.tf
routeros/provider.go
routeros/resource_routing_filter_rule.go
routeros/resource_routing_filter_rule_test.go

feat(routing): Manage Route Filters

---

routeros/resource_interface_ethernet_switch_vlan.go

fix(switch): Incorrect procedure for deleting the resource

---

routeros/resource_interface_ethernet_switch_host.go
routeros/resource_interface_ethernet_switch_rule.go

fix(switch): Correct schema errors

---

routeros/resource_interface_ethernet.go

fix(ethernet): Removed all default values

---

routeros/resource_ip_dhcp_client.go

add script string in dhcp client ressource

dhcp client add script string parameter

---

routeros/resource_ipv6_neighbor_discovery.go

Last PR broke main build avoiding the succesful release of the new version.

Fix max value for MTU - Fix Main

---

routeros/resource_interface_ethernet.go

Fixes #326 (92603541fd6b3f11dcbfd1ff2c1904f6687062a9)

fix: Undo commit "Change l2mtu property "

---

routeros/resource_ipv6_neighbor_discovery.go

Set 90000 (10x JumboFrame) for the upper bound of the MTU.

fix: stop using Int32MaxValue as upper bound for validation

---

examples/resources/routeros_interface_macvlan/import.sh
examples/resources/routeros_interface_macvlan/resource.tf
routeros/provider.go
routeros/resource_interface_macvlan.go
routeros/resource_interface_macvlan_test.go

Tested locally with version > min version.
Added filter for version as the resource was introduced in 1.12.1

feat: Add support for interface macvlan

---

examples/resources/routeros_interface_wireless_cap/import.sh
examples/resources/routeros_interface_wireless_cap/resource.tf
examples/resources/routeros_ip_cloud_advanced/import.sh
examples/resources/routeros_ip_cloud_advanced/resource.tf
examples/resources/routeros_ppp_aaa/import.sh
examples/resources/routeros_ppp_aaa/resource.tf
routeros/provider.go
routeros/resource_interface_wireless_cap.go
routeros/resource_ip_cloud_advanced.go
routeros/resource_ip_cloud_advanced_test.go
routeros/resource_ppp_aaa.go
routeros/resource_ppp_aaa_test.go

This PR adds the following new resources:
- `routeros_ppp_aaa` to manage authentication and accounting;
- `routeros_ip_cloud_advanced` to manage advanced cloud settings;
- `routeros_interface_wireless_cap` resource to manage CAPsMAN client.

feat: Add new resources

---

routeros/resource_ip_service.go

Backward compatibility with ROS 6.x

---

routeros/provider_schema_helpers.go
routeros/resource_wifi.go

fix(Importer): Add extended resource import function

---

examples/data-sources/routeros_files/data-source.tf
examples/resources/routeros_ip_dhcp_relay/import.sh
examples/resources/routeros_ip_dhcp_relay/resource.tf
examples/resources/routeros_ip_upnp/import.sh
examples/resources/routeros_ip_upnp/resource.tf
examples/resources/routeros_ip_upnp_interfaces/import.sh
examples/resources/routeros_ip_upnp_interfaces/resource.tf
routeros/datasource_files.go
routeros/datasource_files_test.go
routeros/provider.go
routeros/provider_schema_helpers.go
routeros/resource_ip_dhcp_relay.go
routeros/resource_ip_dhcp_relay_test.go
routeros/resource_ip_upnp.go
routeros/resource_ip_upnp_interfaces.go
routeros/resource_ip_upnp_interfaces_test.go
routeros/resource_ip_upnp_test.go

fix: Export/import certificates

---

routeros/resource_interface_ethernet_switch_port.go

fix(no-release): Field 'tx_carrier_sense_error' not found in the schema

---

routeros/resource_interface_bridge_port.go

fix(no-release): [Backward compatibility] routeros_interface_bridge_port

---

routeros/provider_schema_helpers.go

flx: Remove the `Default` property from provider_schema_helpers

---

routeros/resource_radius.go

docs(radius): Missing option /radius service=dot1x (and also ipsec)

---

routeros/provider_schema_helpers.go

fix(TimeEquall): Crash when using store_leases_disk in routeros_ip_dhcp_server_config

---

routeros/provider.go
routeros/resource_ovpn_client.go
routeros/resource_ovpn_client_test.go

feat(ovpn): Add routeros_interface_ovpn_client

---

routeros/resource_ip_dhcp_server.go

fix(dhcp-server): Remove default values

---

routeros/resource_ip_firewall_mangle.go

fix(fw-mangle): Fix `dst_address_list` validation

---

examples/resources/routeros_tool_bandwidth_server/resource.tf

Changing the name of the resource in the example for alignment with the API.

Update to documentation bandwidth server ressource

---

routeros/datasource_system_resource.go

fix(routeros_system_resource): Add `bad_blocks` attribute to the ignored ones

---

examples/resources/routeros_ip_dns_adlist/import.sh
examples/resources/routeros_ip_dns_adlist/resource.tf
routeros/provider.go
routeros/resource_ip_dns_adlist.go
routeros/resource_ip_dns_adlist_test.go

feat(resource_dns_adlist): Add dns ad list support

---

routeros/datasource_ip_addresses.go

Add field introduced in 7.16. Hopefully i did this one correct.

Add field introduced in 7.16 - routeros_ip_address

---

routeros/resource_system_user.go

fix: Missing fields in `routeros_system_user ` (introduced in 7.16)

---

routeros/mikrotik_serialize.go
routeros/provider_schema_helpers.go
routeros/resource_interface_wireless.go
routeros/resource_ip_hotspot.go

fix: Unable to remove routeros_interface_wireless from config

---

routeros/resource_file.go

fix(file): Field 'last_modified' not found in the schema

---

routeros/resource_ip_ipsec_identity.go

fix(ipsec): Fix `auth_method` attribute validation

---

routeros/resource_routing_ospf_interface_template_v0.go

fix(ospf): Change the “network” attribute

---

examples/resources/routeros_interface_wireless_connect_list/import.sh
examples/resources/routeros_interface_wireless_connect_list/resource.tf
routeros/provider.go
routeros/resource_interface_wireless_connect_list.go

feat(wave2): Add new resource `routeros_interface_wireless_connect_list`

---

examples/resources/routeros_interface_w60g/import.sh
examples/resources/routeros_interface_w60g/resource.tf
examples/resources/routeros_interface_w60g_station/import.sh
examples/resources/routeros_interface_w60g_station/resource.tf
routeros/provider.go
routeros/resource_interface_w60g.go
routeros/resource_interface_w60g_station.go
routeros/resource_interface_w60g_station_test.go
routeros/resource_interface_w60g_test.go

feat(wifi): Add new resources `routeros_interface_w60g`, `routeros_interface_w60g_station`

---

routeros/resource_interface_bridge_filter.go

fix(bridge_filter): Missing field in interface_bridge_filter

---

examples/resources/routeros_wifi/resource.tf
routeros/resource_wifi_security_multi_passphrase.go

docs: Attach config to wifi

---

routeros/provider.go
routeros/resource_interface_sstp_client.go
routeros/resource_interface_sstp_server.go

This PR adds `resource_interface_sstp_server` and `resource_interface_sstp_client` resources.

feat: add `resource_interface_sstp_*` resources

---

routeros/resource_interface_w60g.go
routeros/resource_interface_w60g_station.go

fix(w60): Fix bugs after the first testing

---

routeros/datasource_ip_dhcp_server_leases.go
routeros/resource_ip_dhcp_server.go

fix(dhcp): Update for ROS 7.17

---

examples/resources/routeros_queue_simple/import.sh
examples/resources/routeros_queue_simple/resource.tf
examples/resources/routeros_queue_type/import.sh
examples/resources/routeros_queue_type/resource.tf
routeros/provider.go
routeros/resource_queue_simple.go
routeros/resource_queue_simple_test.go
routeros/resource_queue_type.go
routeros/resource_queue_type_test.go

feat(queue): Add new resource `routeros_queue_simple`

---

routeros/resource_ip_ssh_server.go
routeros/resource_ipv6_dhcp_client.go
routeros/resource_ipv6_settings.go

fix: Missing fields in the schema with version 7.17.1

---

routeros/mikrotik_client.go
routeros/provider.go

fix(routeros_version): Rename the attribute

---

routeros/resource_wifi_security.go

fix(wifi_security): ft_mobility_domain is a (hex) string, not an integer

---

routeros/mikrotik_resource_drift.go
routeros/mikrotik_resource_drift.yaml
routeros/mikrotik_resource_drift_implementation.go

fix(dhcp-server): 'Bad Request', details: 'unknown parameter src-address

---

examples/resources/routeros_container_mounts/import.sh
routeros/mikrotik_resource_drift.go
routeros/mikrotik_resource_drift.yaml
routeros/resource_container.go

fix(container): Importing containers and container mounts

---

routeros/resource_ip_cloud.go

fix(ip-cloud): IP Cloud ddns_enabled 7.17 and newer

---

routeros/resource_ip_hotspot_walled_garden_ip.go

fix: routeros_ip_hotspot_walled_garden_ip action validation may be incorrect

---

examples/resources/routeros_ip_settings/import.sh
examples/resources/routeros_ip_settings/resource.tf
routeros/provider.go
routeros/resource_ip_settings.go
routeros/resource_ip_settings_test.go

feat(ip-settings): Add new resource `routeros_ip_settings`

---

routeros/resource_ipv6_firewall_filter.go

Add the `fasttrack-connection` action to ipv6 firewall filters.

feat(ipv6_firewall_filter): add action fasttrack-connection

---

routeros/resource_ip_route.go

fix: Resource `routeros_ip_route` schema is missing 2 fields

---

routeros/mikrotik_resource_drift.go
routeros/mikrotik_resource_drift.yaml

fix(ospf_area): NSSA Translator/Translate Schema Error

---

routeros/resource_system_user_sshkeys.go

fix(sshkey): Add `ForceNew` for the `key` attribute

---

routeros/resource_ip_ipsec_peer.go
routeros/resource_ip_ipsec_profile.go
routeros/resource_ip_ipsec_proposal.go

Fix IPSec resource input validation

---

routeros/provider_schema_helpers.go
routeros/resource_system_logging_actions.go

fix(logging_action changed):  Update for ROS 7.18

---

routeros/resource_ip_cloud.go

fix(ip_cloud) Update for ROS 7.18

---

routeros/resource_interface_w60g.go

fix(w60g): Fix the resource creation error

---

routeros/resource_ip_firewall_filter.go
routeros/resource_ip_firewall_mangle.go
routeros/resource_ip_firewall_nat.go
routeros/resource_ip_firewall_raw.go

fix(firewall-v4): Add Set/Unset attributes

---

routeros/resource_ip_service.go

fix(ip-service): routeros_ip_service lead to Warning: Field 'proto' not found in the schema, Warning: Field 'dynamic' not found in the schema

---

routeros/resource_bgp_connection.go
routeros/resource_bgp_template.go
routeros/resource_interface_bonding.go
routeros/resource_ip_dhcp_client.go
routeros/resource_ip_dhcp_server.go
routeros/resource_ipv6_dhcp_client.go
routeros/resource_tool_sniffer.go
routeros/resource_wifi_channel.go
routeros/resource_wifi_datapath.go

fix(ip-dhcp-server): Add an `use_reconfigure` attribute

---

examples/resources/routeros_ip_dns_forwarders/import.sh
examples/resources/routeros_ip_dns_forwarders/resource.tf
routeros/provider.go
routeros/resource_ip_dns_forwarders.go
routeros/resource_ip_dns_forwarders_test.go

feat(ip_dns_forwarders): Add new resource `routeros_ip_dns_forwarders`

---

routeros/datasource_files.go

fix: `last_modified` missing on `routeros_files` datasource

---

routeros/resource_container.go

fix(container): Add a reaction to the start/stop of a container from outside TF

---

routeros/resource_interface_gre6_test.go
routeros/resource_interface_veth.go
routeros/resource_interface_veth_test.go

fix(interface_veth): Add support for multiple addresses on the interface

---

routeros/resource_ipv6_firewall_filter.go

fix(ipv6-firewall): Wrong allowed values for `reject_with` field

---

examples/resources/routeros_interface_detect_internet/import.sh
examples/resources/routeros_interface_detect_internet/resource.tf
routeros/provider.go
routeros/resource_interface_detect_internet.go
routeros/resource_interface_detect_internet_test.go

feat(detect-internet): Add new resource `routeros_interface_detect_internet`
