routeros/resource_interface_bridge.go
According to [offcial docs](https://help.mikrotik.com/docs/display/ROS/Bridging+and+Switching) pvid should be within range of 1 to 4094 defaulting to 1
Fixes: #73
=> fix: pvid defaults to 1

.github/scripts/setup_routeros.py, client/system_identity.go, client/system_identity_test.go, routeros/provider.go, routeros/resource_system_identity.go, routeros/resource_system_identity_test.go
Because we cannot 'delete' a System Identity we just reset it back to the default `MikroTik`. If that's not the best idea, we can instead just make the delete a 'no op' and skip it.
Closes #55
=> /system/identity set/get

routeros/resource_interface_bridge.go
Reverts GNewbury1/terraform-provider-routeros#103
Fixes #104
=> Revert "fix(#102): Change property ID for bridge"

routeros/resource_ip_dhcp_server_lease.go
Adds the following missing fields to DhcpServerLease
- `active_address`
- `active_hostname`
- `active_mac_address`
Fixes #110
=> fix(#110): Add missing fields to DhcpServerLease

routeros/resource_ip_dns_record.go
=> fix: routeros_ip_dns_record - field type is missing

routeros/resource_ip_dns.go, routeros/resource_ip_dns_test.go
=> fix: routeros_ip_dns - new fields in 7.8

routeros/resource_interface_vrrp.go
Using RouterOS 7.7 we are facing errors related to the group used by multiple VRRP interface:
```
Error: from RouterOS device: input does not match any value of group-master
with routeros_interface_vrrp.interface_vrrp["4"],
on vrrp.tf line 3, in resource "routeros_interface_vrrp" "interface_vrrp":
3: resource "routeros_interface_vrrp" "interface_vrrp" {
```
when declaring a VRRP interface:
```
resource "routeros_interface_vrrp" "interface_vrrp" {
for_each  = { for interface in local.interfaces : interface.interface_id => interface }
interface = "ether${each.value.interface_id}"
name      = "vrrp${each.value.interface_id}"
comment   = "${each.value.comment}_gw"
priority  = "200"
vrid      = "42"
}
```
This change remove the default value to avoid providing a group name on the interface to …
=> fix: Remove default for VRRP interface group

routeros/resource_ip_dns.go
Fixes #174
Setting the "servers"  and "use_doh_server" fields to an empty value.
Setting the "allow_remote_requests"  and "verify_doh_cert" fields to a false value.
=> fix: dns servers cannot be removed

examples/resources/routeros_ip_pool/resource.tf, examples/resources/routeros_system_scheduler/resource.tf, routeros/provider_schema_helpers.go, routeros/resource_system_identity.go
Preserving the integrity of resource management with the key field "name" when renaming them
Fixes #192
=> fix: Fix the creation of resources when renaming them

examples/resources/routeros_interface_pppoe_client/import.sh, examples/resources/routeros_interface_pppoe_client/resource.tf, routeros/provider.go, routeros/resource_interface_pppoe_client.go, routeros/resource_interface_pppoe_client_test.go
=> feat: Add support for /interface/pppoe-client

routeros/resource_ipv6_firewall_addr_list.go
Unlike with ipv4 address lists, routeros will add a /128 netmask when an ip w/o netmask is given as input. Add a DiffSuppressFunc to not have changing plans every run.
=> fix: ipv6 addr-list addr w/o netmask adds /128 netmask

routeros/resource_ip_firewall_mangle.go
Fix after getting this error message:
```
Error: expected action to be one of [accept add-dst-to-address-list add-src-to-address-list change-dscp change-mss change-ttl clear-df fasttrack-connection jump log mark-connection mark-packet mark-routing passthrough  return route set-priority sniff-pc sniff-tzsp strip-ipv4-options], got passthrough
```
=> Remove extra space after passthrough in validation

examples/resources/routeros_ip_cloud/import.sh, examples/resources/routeros_ip_cloud/resource.tf, routeros/provider.go, routeros/resource_ip_cloud.go, routeros/resource_ip_cloud_test.go
=> feta: Add IP Cloud

routeros/resource_snmp.go
=> fix: Add SNMP Settings

docs/index.md, templates/index.md.tmpl
Small change to the provider docs to list out the allowable url schemes.
This caught me up for a moment since `http` isn't actually allowed. I documented only the `api` and `apis` schemes, leaving `https` undocumented.
`https`, while allowed, is confusing in its own way since without a port specified 443 would be assumed by most, not 8729.
=> Document allowed url schemes

examples/resources/routeros_system_logging/import.sh, examples/resources/routeros_system_logging/resource.tf, routeros/provider.go, routeros/resource_system_logging.go, routeros/resource_system_logging_test.go
This enables configuring the rules of logging for RouterOS
=> Implement routeros_system_logging resource

routeros/resource_interface_ethernet.go
A simple clean up, I was not aware that funtion already existed.
=> Clean custom serach filter with builtin

routeros/mikrotik_client.go
=> fix: Fix double slash at the end of a hostname

routeros/resource_capsman_channel.go, routeros/resource_capsman_manager.go
This PR fixes the following:
- add some missing values in the `routeros_capsman_channel` resource;
- fix `routeros_capsman_manager .upgrade_policy` to accept `suggest-same-version` instead of `suggest-same-upgrade`.
=> fix: Fix enumerated values in CAPsMAN resources

docs/resources/interface_eoip.md, routeros/mikrotik_serialize.go, routeros/resource_interface_eoip.go
While working on #283, I discovered that optional numeric fields with `0` as a default value are skipped even though they appear in the planned changes. That also takes place when we use `0` in the configuration, and the related field either has no default value or has `0` in there:
```go
"tunnel_id": {
Type:        schema.TypeInt,
Optional:    true,
Default:     0,
Description: "Unique tunnel identifier, which must match the other side of the tunnel.",
},
```
```terraform
resource "routeros_interface_eoip" "eoip2" {
name           = "eoip2"
}
```
```
Terraform will perform the following actions:
+ resource "routeros_interface_eoip" "eoip2" {
+ actual_mtu                 = (known after apply)
+ allow_fast_path            = true
+ arp                        = "enabled"
+ arp_timeout …
```
=> fix: Fix empty value check to handle default numeric values correctly

examples/resources/routeros_ip_dhcp_server_config/import.sh, examples/resources/routeros_ip_dhcp_server_config/resource.tf, routeros/provider.go, routeros/resource_ip_dhcp_server_config.go
This PR adds missing DHCP-server config resource. The schema diverges in only one property -- `radius-password` was added in 7.0.
=> feat: Add DHCP server config resource

.github/workflows/module_testing.yml, .github/workflows/release.yml, README.md
Error: ../../../go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/terraform/state.go:321:16: undefined: errors.Join
note: module requires Go 1.20
=> Bump Go version from 1.19 to 1.21

routeros/resource_interface_bridge_port.go, routeros/resource_interface_ethernet.go, routeros/resource_ip_firewall_connection_tracking.go, routeros/resource_ip_firewall_connection_tracking_test.go, routeros/resource_ip_firewall_filter.go, routeros/resource_ip_firewall_mangle.go, routeros/resource_ip_firewall_nat.go, routeros/resource_ipv6_firewall_filter.go, routeros/resource_system_logging.go, routeros/resource_system_user.go
While working with the provider, I discovered that it changes the Terraform state on every apply, even though there are no changes. That's caused by constantly changing stats fields (e.g., number of transferred bytes or packets). That breaks the whole concept of the Terraform state and produces state changes without actual "infrastructure" change.
Apart from that, some resources returned many warnings related to the missing schema fields.
This PR tries to address those problems in a backward-compatible way by reusing the `MetaSkipFields` property:
1. Skip stats for the ethernet resources, which were causing a lot of noise in the output (resolves #298).
2. Skip stats for the firewall rules.
3. Skip debug fields from the bridge ports.
4. Skip the last login information for the system users. …
=> fix: Skip computed stat fields

examples/resources/routeros_radius/import.sh, examples/resources/routeros_radius/resource.tf, examples/resources/routeros_radius_incoming/import.sh, examples/resources/routeros_radius_incoming/resource.tf, routeros/provider.go, routeros/resource_radius.go
This PR adds [RADIUS](https://help.mikrotik.com/docs/display/ROS/RADIUS) resources. The change is compatible with both `6.x` and `7.x` versions, even though the `vrf` property is introduced only in `7.4`.
=> feat: Add RADIUS resources

examples/resources/routeros_system_user_aaa/import.sh, examples/resources/routeros_system_user_aaa/resource.tf, examples/resources/routeros_system_user_group/import.sh, examples/resources/routeros_system_user_group/resource.tf, examples/resources/routeros_system_user_settings/import.sh, examples/resources/routeros_system_user_settings/resource.tf, routeros/provider.go, routeros/provider_schema_helpers.go, routeros/provider_schema_helpers_test.go, routeros/resource_system_user_aaa.go, routeros/resource_system_user_aaa_test.go, routeros/resource_system_user_group.go, routeros/resource_system_user_group_test.go, routeros/resource_system_user_settings.go, routeros/resource_system_user_settings_test.go
This PR adds the following resources:
- `routeros_system_user_aaa`;
- `routeros_system_user_group`;
- `routeros_system_user_settings`.
=> feat: Add missing system user resources

examples/resources/routeros_ip_dhcp_client_option/import.sh, examples/resources/routeros_ip_dhcp_client_option/resource.tf, routeros/provider.go, routeros/resource_ip_dhcp_client option.go, routeros/resource_ip_dhcp_client_option_test.go
=> add dhcp client option

routeros/resource_interface_ethernet.go
On latest version of Router OS: 7.13.4 The following warnings are pressent for interfaces of type ethernet:
```
│ Warning: Field 'tx_rx_1024_max' not found in the schema
│ 
│   with routeros_interface_ethernet.eths["core-link-2"],
│   on interfaces.tf line 87, in resource "routeros_interface_ethernet" "eths":
│   87: resource "routeros_interface_ethernet" "eths" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: ▷ 'tx_rx_1024_max': '2557838' ◁
│ Warning: Field 'tx_unicast' not found in the schema
│ 
│   with routeros_interface_ethernet.eths["core-link-2"],
│   on interfaces.tf line 87, in resource "routeros_interface_ethernet" "eths":
│   87: resource "routeros_interface_ethernet" "eths" {
│ 
│ [MikrotikResourceDataToTerraform] The field was lost …
```
=> Add missing ethernet interface fields to SkipFields

examples/resources/routeros_wifi/import.sh, examples/resources/routeros_wifi/resource.tf, routeros/provider.go, routeros/provider_schema_helpers.go, routeros/resource_interface_ethernet.go, routeros/resource_wifi.go, routeros/resource_wifi_configuration.go
The goal of this PR is to add support for managing WiFi interfaces, but that required some additional changes:
- Refactored `AlwaysPresentNotUserProvided` helper to handle map types correctly.
- Moved L2 MTU property into a reusable helper.
- Fixed `routeros_wifi_configuration` to align with the newly introduced `routeros_wifi`.
=> feat: Add `routeros_wifi` resource to manage WiFi interfaces

routeros/resource_interface_bridge_vlan.go, routeros/resource_interface_ethernet.go, routeros/resource_ovpn_server.go
This PR adds/fixes the following:
- Skip the newly introduced `debug_info` property in the `routeros_interface_bridge_vlan` resource - added in 7.14.
- Add the newly introduced `push_routes` property to the `routeros_ovpn_server` resource - added in 7.14.
- Fix corrupted skipped fields meta property in `routeros_interface_ethernet` - regression from #359.
=> feat: Resolve warnings due to some missing properties

examples/resources/routeros_zerotier/import.sh, examples/resources/routeros_zerotier/resource.tf, examples/resources/routeros_zerotier_controller/import.sh, examples/resources/routeros_zerotier_controller/resource.tf, examples/resources/routeros_zerotier_interface/import.sh, examples/resources/routeros_zerotier_interface/resource.tf, routeros/provider.go, routeros/resource_zerotier.go, routeros/resource_zerotier_controller.go, routeros/resource_zerotier_interface.go
This PR adds [ZeroTier](https://help.mikrotik.com/docs/display/ROS/ZeroTier) support with self-sufficient examples using the [`zerotier/zerotier`](https://registry.terraform.io/providers/zerotier/zerotier/latest) provider.
The following resources have been implemented:
- `routeros_zerotier` to manage ZeroTier instances;
- `routeros_zerotier_interface` to manage ZeroTier interface;
- `routeros_zerotier_controller` to manage ZeroTier controller.
=> feat: Add ZeroTier support

README.md, docs/index.md, routeros/mikrotik_client.go, routeros/provider.go, templates/index.md.tmpl
This PR enables the `http` scheme support in the connection settings.
=> feat: Add `http` scheme support for the REST API

routeros/provider_schema_helpers.go, routeros/provider_schema_helpers_test.go, routeros/resource_ip_firewall_filter.go
=> fix(no-release): [Backward compatibility] routeros_ip_firewall_filter NOT WORKING AS EXPECTED

routeros/resource_interface_bridge_port.go
=> [Backward compatibility] routeros_interface_bridge_port 

routeros/resource_ip_firewall_filter.go, routeros/resource_ipv6_firewall_filter.go
Previously, when you attempted to update a firewall rule with a non-null `protocol` field by removing said field, the serializer would set `protocol` to an empty string instead of completely omitting the value, resulting in API errors and ultimately causing the apply job to fail.
I.e, assuming that you have applied the following:
```terraform
resource "routeros_ip_firewall_filter" "rules" {
chain    = "input"
action   = "accept"
protocol = "tcp"
}
```
and then change it to this:
```terraform
resource "routeros_ip_firewall_filter" "rules" {
chain    = "input"
action   = "accept"
}
```
The apply would fail with the following API error:
```
2024-04-26T15:40:51.919+0200 [ERROR] vertex "routeros_ip_firewall_filter.rules" error: PATCH 'https://192.168.88.2
18/rest/ip/firewall/filter/*A' …
```
=> fix: properly unset firewall filter rule `protocol` field when removed

examples/resources/routeros_system_certificate/resource.tf, routeros/mikrotik_client.go, routeros/mikrotik_client_api.go, routeros/mikrotik_client_rest.go, routeros/provider_test.go, routeros/resource_system_certificate.go, routeros/resource_system_certificate_test.go, routeros/resource_testing_helper.go
* add ability to sign certificates with scep (`add-scep` command)
* add missing computed `challenge_password` parameter (present only with scep client)
* add a couple of tests for resource updating, resource attributes are checked from the actual API
* `ForceNew` is not enough on `sign` set. It need to be set on all elements or recreation won't work
There are still some quirks I found:
1. If for the following resources:
```tf
resource "routeros_system_certificate" "root_ca" {
name        = "Test-Root-CA"
common_name = "RootCA"
key_usage   = ["key-cert-sign", "crl-sign"]
trusted     = true
sign {
}
}
resource "routeros_system_certificate" "server_crt" {
name        = "Server-Certificate"
common_name = "server.crt"
key_usage = ["digital-signature", "key-encipherment", "tls-server"]
sign { …
```
=> feat: add ability to sign certificates with scep

docs/resources/wifi.md, routeros/resource_wifi.go
I wanted to manage the wifi interfaces on my router and I noticed that the `comment` property isn't part of the `routeros_wifi` resource schema. So I thought I add it. I've tested it by locally building the binary and running it with terraform, everything seemed to worked correctly.
This is my first contribution to this repository. I haven't found any rules in the repo so I hope this pull request is okay. Let me know if I should change something or add something.
=> feat: add comment to routeros_wifi resource

routeros/resource_ip_dhcp_server.go
The default value for `auto_mac` is false, and `lease_time` 30m, but if unspecified they're assumed true and 10m respectively; so a plan with them unspecified and having imported the default configuration from a freshly reset routeros wants to change them.
=> Fix unintended plan diff from unspecified defaults

routeros/provider.go, routeros/resource_ip_firewall_raw.go, routeros/resource_ip_firewall_raw_test.go
=> feat(firewall/raw): Add new resource

templates/resources/system_certificate.md.tmpl
=> docs(certificate-sign): Add a little help on certificate signing

routeros/resource_interface_vrrp.go
=> fix(vrrp): Add handling of the `group-authority` attribute

routeros/resource_interface_bridge.go, routeros/resource_interface_bridge_port.go, routeros/resource_interface_bridge_vlan.go, routeros/resource_interface_vlan.go
=> feat(mvrp): Support Multiple VLAN Registration protocol (MVRP).

docs/resources/snmp_community.md, routeros/resource_snmp_community.go
Fixes #495
This uses the `Any` ability of the Terraform validation library to do either bare ipv4 or ipv6 addresses (which by observing the device essentially become /32 networks) and CIDR networks.
I wasn't sure what to update test-wise, could use help there.
=> fix(snmp-community): Allow a set of `addresses`

routeros/provider_schema_helpers.go, routeros/resource_interface_ethernet.go, routeros/resource_interface_macvlan.go, routeros/resource_ppp_aaa.go, routeros/resource_radius.go, routeros/resource_user_manager_settings.go, routeros/resource_wifi_cap.go, routeros/resource_wifi_channel.go
This PR is mostly about adding newly added properties in the 7.15 release:
- `sfp_ignore_rx_los` to `routeros_interface_ethernet`;
- `enable_ipv6_accounting` to `routeros_ppp_aaa`;
- `require_message_auth` to `routeros_radius`;
- `require_message_auth` to `routeros_user_manager_settings`;
- `reselect_interval` to `routeros_wifi_channel`;
- `current_caps_man_address` to `routeros_wifi_cap`;
- `current_caps_man_identity` to `routeros_wifi_cap`.
On top of that, RouterOS 7.15 started _always_ returning an empty value in `routeros_wifi_configuration` (`/rest/interface/wifi/configuration`):
```
"aaa.password-format": "",
```
Since checking empty old values in the `AlwaysPresentNotUserProvided` helper makes no sense in the first place, we can safely remove this condition. The removal didn't …
=> feat: Add some new properties introduced in RouterOS 7.15

examples/resources/routeros_ovpn_server/resource.tf, routeros/resource_ovpn_server.go, routeros/resource_ovpn_server_test.go, routeros/resource_ovpn_server_v0.go
- This PR is similar to #501 in migrating `auth`, `cipher`, and `redirect_gateway` to multi-value properties.
- Also, this PR sets correct default values for `require_client_certificate`, `enable_tun_ipv6 `, and `tls_version`.
- Lastly, it also fixes the `certificate` property not to send it when unset.
=> feat: Update the `routeros_ovpn_server` resource to handle some properties correctly

routeros/resource_routing_ospf_interface_template.go
I couldn't find the exact OS version on which the attribute change occurred. At least since 7.10 the attribute is new, but on 6.48 it is old.
Fixes #510
=> fix(ospf_interface_template): RouterOS 7.x & OSPF Interface Template Auth Key

routeros/resource_system_certificate.go
Fixed incorrect import condition for certificates with private key. Added `AlwaysPresentNotUserProvided` function for `X509 Subject` attributes.
Fixes #511
=> fix(certificate): Certificate import ambiguous value of file-name

routeros/resource_interface_bridge.go, routeros/resource_ip_dhcp_server_lease.go, routeros/resource_ip_dhcp_server_option.go, routeros/resource_ip_dhcp_server_option_sets.go, routeros/resource_ip_dns.go, routeros/resource_ip_neighbor_discovery.go, routeros/resource_ip_service.go, routeros/resource_wifi_provisioning.go
This PR brings the following:
- add the `comment` property support to the DHCP resources;
- remove the default value for the `radio_mac` property in the `routeros_wifi_provisioning` resource (closes #508);
- add `slave_name_format` property support to the `routeros_wifi_provisioning` resource;
- add `class_id` property support to the `routeros_ip_dhcp_server_lease` resource;
- add `forward_reserved_addresses` property support to the `routeros_interface_bridge` resource;
- add `max_sessions` property support to the `routeros_ip_service` resource;
- add `discover_interval` property support to the `routeros_ip_neighbor_discovery_settings` resource;
- add `lldp_vlan_info` property support to the `routeros_ip_neighbor_discovery_settings` resource;
- add `mdns_repeat_ifaces` property support to …
=> feat: Add newly introduced properties from the most recent RouterOS

.gitignore, routeros/mikrotik_serialize.go, routeros/resource_system_user_group.go
Added policy set processing for user groups. To work correctly, we need to analyze incoming changes and modify outgoing policy set values at the same time. The minimum version for the provider build go `v1.21`, since the `slices.Contains()` function is used. Fixes #544
=> Fix change detection in sets with `SetUnset` values

routeros/resource_interface_ethernet.go
Adding skip fields due to warnings seen when using `routeros_interface_ethernet` in provider.
> NOTE: I have not tested, formatted or linted. I am not experienced in GO language or how to compile/test for these updates, but I believe this simple fix would get rid of the warnings.
=> Adding fields to skip for rx and tx on resource_interface_ethernet.go

routeros/resource_wifi_security.go
Fix incorrect validation added for the resource attribute `routeros_wifi_security.wps`.
Fixes #577
=> fix: validation for routeros_wifi_security.wps

examples/resources/routeros_bridge_mlag/import.sh
Import example was wrong for the `routeros_bridge_mlag`.
=> docs: fix mlag import example

routeros/datasource_system_routerboard.go
=> fix(ds): warning  Field 'revision' not found in the schema in routeros_system_routerboard datasource

routeros/resource_ipv6_dhcp_client.go, routeros/resource_ipv6_dhcp_client_test.go
=> fix: routeros_ipv6_dhcp_client prefix_hint validation issue

examples/resources/routeros_ipv6_firewall_mangle/import.sh, examples/resources/routeros_ipv6_firewall_mangle/resource.tf, examples/resources/routeros_ipv6_firewall_nat/import.sh, examples/resources/routeros_ipv6_firewall_nat/resource.tf, routeros/datasource_ipv6_firewall.go, routeros/datasource_ipv6_firewall_mangle.go, routeros/datasource_ipv6_firewall_nat.go, routeros/provider.go, routeros/resource_ipv6_firewall_mangle.go, routeros/resource_ipv6_firewall_mangle_test.go, routeros/resource_ipv6_firewall_nat.go, routeros/resource_ipv6_firewall_nat_test.go
Add `routeros_ipv6_firewall_nat` and `routeros_ipv6_firewall_mangle` which were still missing I need.
Behavior should pretty much match the ipv4 version minus the missing options.
=> Add new resources `routeros_ipv6_firewall_nat` and `routeros_ipv6_firewall_mangle`

routeros/resource_ip_dhcp_relay.go
=> fix(ip_dhcp_relay): Field 'dhcp_server_vrf' not found in the schema

routeros/provider.go, routeros/resource_tool_email.go, routeros/resource_tool_email_test.go
Hi! Needed this in my setup, figured it would be a nice thing to have in this provider.
I'm not very fluent at Go, so please let me know if anything is wrong. Thanks for your time reviewing this!
Compiled and tested this locally.
=> feat(tool): add new resource `routeros_tool_email`

routeros/datasource_ipv6_firewall_nat.go, routeros/resource_ipv6_firewall_nat.go
Fixup for my previous PR. IPv6 NAT rules do not have a `to_addresses` field instead it is a `to_address` field.
=> fix(ipv6_firewall_net): ipv6_firewall_nat has to_address not to_addresses

routeros/datasource_interface_bridge_filter.go
Fixes a bug that results in an empty data object every time due to: `[MikrotikResourceDataToTerraformDatasource] the datasource Schema field was lost during development: ▷ 'data' ◁`
[Schema](https://github.com/terraform-routeros/terraform-provider-routeros/blob/a97fe34287072f1993e8134ab31f3909d37fe024/routeros/datasource_interface_bridge_filter.go#L20) shows the key is `filters`
=> fix(datasource_routeros_interface_bridge_filter): Returned data key should be `filters`

examples/resources/routeros_system_certificate/resource.tf, routeros/resource_file.go, routeros/resource_system_certificate.go
=> fix: Importing certificate and key without `routeros_file` resource

routeros/provider_schema_helpers.go, routeros/resource_interface_vrrp.go, routeros/resource_interface_vrrp_v0.go
The short char for minutes is a lower 'm' not the upper. (upper is for month, but i dont think mikrotik is use anywhere)
This patch fix that.
=> fix: minutes short name is lower m

routeros/resource_ipv6_settings.go
Hello,
This should fix the following warnings :
> Warning: Field 'ipv6_fast_path_packets' not found in the schema
> Warning: Field 'ipv6_fasttrack_active' not found in the schema
> Warning: Field 'ipv6_fasttrack_bytes' not found in the schema
> Warning: Field 'ipv6_fasttrack_packets' not found in the schema
> Warning: Field 'allow_fast_path' not found in the schema
> Warning: Field 'ipv6_fast_path_active' not found in the schema
> Warning: Field 'ipv6_fast_path_bytes' not found in the schema
> Warning: Field 'disable_link_local_address' not found in the schema
=> fix(ipv6-settings): Add new attributes (ROS 7.18)

routeros/resource_interface_ethernet.go
=> fix(ethernet): Ethernet `advertise` do not allow multiple values

docs/data-sources/interfaces.md, routeros/datasource_interfaces.go
Fixes the following warning:
```
╷
│ Warning: Field 'inactive' not found in the schema
│ 
│   with data.routeros_interfaces.main,
│   on main.tf line 57, in data "routeros_interfaces" "main":
│   57: data "routeros_interfaces" "main" {
│ 
│ [MikrotikResourceDataToTerraformDatasource] the field was lost during the Schema development: ▷ 'inactive': 'false' ◁
╵
```
The `inactive` field is present (at least) on `type=lte` interfaces.
=> fix: `routeros_interfaces` data source schema is missing "inactive" field

routeros/provider_schema_helpers.go, routeros/resource_interface_wireguard_peer.go
Fix wireguard peer persistent-keepalive validation: it's time duration (5s, 10m, 1h, etc).
You can set a decimal value, but mikrotik will convert it to duration, so terraform always want to change it to integer back.
=> Implement duration check

routeros/mikrotik_resource_drift_implementation.go
The result map was located in the wrong place.
[ROS 7.18, 1.85.0] wireguard peers' responder/is_responder parameter broken again
Fixes #750
=> fix(wg-peers): Fix drift attributes

routeros/resource_interface_bridge_port.go
Hello,
This should fix the following warnings :
> Warning: Field 'designated_bridge_id' not found in the schema
>   Warning: Field 'designated_port_id' not found in the schema
>   Warning: Field 'discard_transitions' not found in the schema
>   Warning: Field 'forward_transitions' not found in the schema
>   Warning: Field 'last_topology_change' not found in the schema
>   Warning: Field 'port_id' not found in the schema
>   Warning: Field 'rx_bpdu' not found in the schema
>   Warning: Field 'rx_tc' not found in the schema
>   Warning: Field 'topology_changes' not found in the schema
>   Warning: Field 'tx_bpdu' not found in the schema
>   Warning: Field 'tx_tc' not found in the schema
=> fix(bridge_port): Add new attributes (ROS 7.19)

routeros/resource_ip_ipsec_identity.go
This pull request corrects the validation for the `my_id` and `remote_id` attributes in the `routeros_ip_ipsec_identity` resource.
By removing the `ValidateFunc`, this change allows users to provide the required `type:value` string format (e.g., "user-fqdn:user@example.com"), which was previously impossible.
Fixes #774
=> Fix(ipsec): Correct validation for my_id and remote_id attributes in ipsec_identity

routeros/resource_interface_wireless.go
The 2ghz-g/n band is supported on RBGrooveGA-52HPacn at least, and I'm pretty sure I've seen it on others.
```
[admin@skynet1] > /interface/wireless/set wlan1 band=
2ghz-b       2ghz-b/g/n     2ghz-onlyg     5ghz-a       5ghz-a/n/ac     5ghz-onlyac   
2ghz-b/g     2ghz-g/n       2ghz-onlyn     5ghz-a/n     5ghz-n/ac       5ghz-onlyn    
```
=> fix(wireless): Support 2ghz-g/n band specification
